### ISSUE TITLE
General UI improvements

### ISSUE THREAD

**Issue by novase** [NovaInfiniteLoops/Hangman-Team#44]
Larger text, clearer text, 

Perhaps a subtle repeating background image - a texture image.

Positioning of various elements.

How can we make it look even prettier than it is?

**Comment by kohakuhub** [comment]
The issue with larger text is that we're already having issues with all components fitting on irregular screen sizes (mostly laptops).

**Comment by novase** [comment]
Two possible solutions.   As I've said before, css is not one of my core
skills but perhaps Amber can evaluate these two possible solutions:


   - Since we are already using Bootstrap, let's leverage the column width
   features included - eg <div class="col-xs-4"> etc.   The advantage here is
   that we can build easily build a website that looks different on phones,
   tables, large monitors etc in addition to fixing the underlying issues.
    The code refactoring here should be a minor task.
   - Isn't there a way in CSS to define element widths as a relative
   percentage of the screen rather than a defined pixel size?

Would either of those approaches merit further consideration?

Regards,

Tom

**Comment by kohakuhub** [comment]
I can define elements as taking up a certain % of the screen but I don't know enough about Bootstrap to say whether or not columns are possible.... I already had to remove the col-xs-12 class from the main image because it was making the image too large.

**Comment by ilginem** [comment]
Do we feel this issue is resolved?

**Comment by kohakuhub** [comment]
I've done what I can wrt appropriate resizing. The screen still gets weird
when you resize it very small, but it should work fine on most computers
and tablets.

On Mon, Nov 30, 2015 at 1:40 AM, ilginem <notifications@github.com> wrote:

> Do we feel this issue is resolved?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NovaInfiniteLoops/Hangman-Team/issues/44#issuecomment-160534696>
> .
>



-- 
-AV

**Comment by novase** [comment]
I think it looks phenomenal.   Great job on turning it into a single page web app.

I wouldn’t worry about the sizing issues - we’ll just make sure that the machine we use for the presentation will not have it.

**Comment by ilginem** [comment]
It looks very nice. I would just close this issue.

Emre
